### ISSUE TITLE
对于代码效率和精度的测试

### ISSUE THREAD

**Issue by An-314** [An-314/qrupdate#1]
我已经完成了`dqrinc`和`dqrdec`的编译，已经放在了[release](https://github.com/An-314/qrupdate/releases)中（包括简化QR分解和完整QR分解两种输入）

现在我们需要测试代码的稳定性和运行效率。

> 我尝试了一下，感觉更新的过程算得很快，在6000*4000的规模下只需要0.4秒。

## 但是如何判断稳定性？

@hu-yy211 有没有什么方法判断精度？

我现在使用的是`numpy`的`np.allclose`判断A经过变动（加减一列）和Q_1*R_1的差距。

这样反应`dqrinc`是通过`np.allclose`的，而`dqrdec`是没有通过的。但是我在查看`dqrdec`测试样例的结果时候，发现他们的差距并不大，大约能控制在e-13。大概可以证明`dqrinc`的精度是很不错的。（但矩阵乘法的精度损会有影响吗？）

**Comment by An-314** [comment]
[A_updated.txt](https://github.com/An-314/qrupdate/files/13625134/A_updated.txt)
[A_reconstructed.txt](https://github.com/An-314/qrupdate/files/13625135/A_reconstructed.txt)

这是上面提到的没有通过`np.allclose`的`dqrdec`的结果，我感觉他们两个相差还是不算太大的（甚至很小）

**Comment by hy-z22** [comment]
用python重写的也改完了，不过我只用简单的实例测了一下，还没试大规模矩阵，要是测精度的话也可以一起

**Comment by An-314** [comment]
如果python两个人都写完了，我也把它变成一个包，然后我们可以同时测试这两个
@hu-yy211 @hy-z22 你们都写完了吗

**Comment by An-314** [comment]
下面我考虑对一个矩阵不断用两个函数进行插入或删除，然后通过对比新的QR乘积与A经过操作后的矩阵，查看在多次操作的误差，从而判断稳定性

你们还有什么好的方法吗

**Comment by An-314** [comment]
通过先后计算

- $A$ 与 $QR$ 的误差
- $Q^TQ$ 与 $I$ 的误差
- $R^TR$ 与 $A^TA$ 的误差

来测试，[结果](https://github.com/An-314/qrupdate/tree/Windows/test_py)表明还不错。
