### ISSUE TITLE
解决python_convert代码的错误

### ISSUE THREAD

**Issue by An-314** [An-314/qrupdate#2]
@hu-yy211 提出 现在python的代码可以运行，但结果有问题（R不是上三角）

检查一下函数及其依赖的正确性。目前只需要`dqrinc`与`dqrdec`这两个函数。它们的依赖是：
`dgqvec` `dqhqr` `dqrot` `dqrqh` `dqrtv1`都需要检查。

**Comment by hy-z22** [comment]
哪一个有问题，两个都有？

**Comment by hu-yy211** [comment]
dqrinc



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月10日(周日) 中午11:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [An-314/qrupdate] 解决python_convert代码的错误 (Issue #2)




 
哪一个有问题，两个都有？

**Comment by An-314** [comment]
`dqrdec`有测试吗？

**Comment by An-314** [comment]
有明确两个函数的输入输出的矩阵规模吗
Fortran的版本要求`dqrinc`输入的（简化QR分解）矩阵是m*(n+1)与(n+1)*(n+1)的，这是为了给扩充一行留出空间；但python可能因为语言特性需不需要需要明确一下

**Comment by hu-yy211** [comment]
修改过了，否则运行不了。现在能出结果，但结果是错误的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月10日(周日) 中午11:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [An-314/qrupdate] 解决python_convert代码的错误 (Issue #2)




 
有明确两个函数的输入输出的矩阵规模吗
 Fortran的版本要求dqrinc输入的（简化QR分解）矩阵是m*(n+1)与(n+1)*(n+1)的，这是为了给扩充一行留出空间；但python可能因为语言特性需不需要需要明确一下

**Comment by An-314** [comment]
我上传了测试文件，现在你们可以在`./test-py/`下找到测试文件

现在修改可以在`.\python_convert\qrupdate`目录下修改，这个就是我们之后要编译的包

**Comment by An-314** [comment]
我看了一下`dqrdec`的结果，虽然没通过`np.allclose`但是我看结果和`f2py`编译下来的差不多

`dqrinc`现在不支持完全QR分解；但是`dqrdec`支持

现在`dqrinc`的简化QR输出结果也不正确

**Comment by hy-z22** [comment]
我改完了

**Comment by hy-z22** [comment]
> 我上传了测试文件，现在你们可以在`./test-py/`下找到测试文件
> 
> 现在修改可以在`.\python_convert\qrupdate`目录下修改，这个就是我们之后要编译的包

你是把文件直接粘过去了吗

**Comment by An-314** [comment]
我改了一下import的方式，内容没变

包内部函数调用现在只用写名字不用写xx.xx了

外部接口写qrupdate.dqrinc，可以参照一下测试文件

现在要修改直接在qrupdate目录下修改就好了，我只是改了调用函数的方式，其他什么都没改

**Comment by hy-z22** [comment]
呃那我也改一下import方式

**Comment by An-314** [comment]
直接在qrupdate目录下修改就好了，不管src了fetch下来继续改

**Comment by An-314** [comment]
完成，并调整了接口
