### ISSUE TITLE
DQRDECpython实现的问题

### ISSUE THREAD

**Issue by An-314** [An-314/qrupdate#3]
现在DQRDEC的python初步实现仍有问题

@hy-z22 @hu-yy211 针对下面的问题对代码进行重新的修改和测试

## 对于我们比较Q'R'与A[-j列]的比较

对于测试样例是10*5的矩阵减去第2行：
![2b8d6cdffe49ef0e23401551f88520e](https://github.com/An-314/qrupdate/assets/129043126/8219d998-5d81-4ace-8f18-cc1059b27f84)
可以看到每行第二列的是有问题的

## 对于DQRDEC的输出结果

应该m n的简化QR分解是 m*n 和 n*n
那么dqrdec输出的规模是m * (n-1)与(n-1)*(n-1)

现有代码输出结果的规模是m * n与n*(n-1)

但即使是这样，无论是否删去那一行一列，都出现A的一列不对

## Fortran的正确性还没有进行验证，后面需要验证

因为前面提到过精度问题，但是没有细看。后面 @An-314  再进行详细检查。

**Comment by hy-z22** [comment]
改完了
